### ISSUE TITLE
The body of a for in should be wrapped in an if statement to filter unwanted properties from the prototype.

### ISSUE THREAD

**Issue by wolfy1339** [Brilliant-Minds/Brilliant-Minds.github.io#9]
#### Occurred on:
+ **Commit**:  dacf7ee25b0069ed1cf6a2c7f65ff4ab1219ced1
+ **File**:    [members.js](https://github.com/Brilliant-Minds/Brilliant-Minds.github.io/blob/dacf7ee25b0069ed1cf6a2c7f65ff4ab1219ced1/members.js)
+ **LineNum**: [169](https://github.com/Brilliant-Minds/Brilliant-Minds.github.io/blob/dacf7ee25b0069ed1cf6a2c7f65ff4ab1219ced1/members.js#L169)
+ **Code**:    `        for (var i in e.awards) {`

    
#### Currently on:
+ **Commit**:  e9b4f2f1d14a67a061d3df840d20bfc6f3463e24
+ **File**:    [members.js](https://github.com/Brilliant-Minds/Brilliant-Minds.github.io/blob/e9b4f2f1d14a67a061d3df840d20bfc6f3463e24/members.js)
+ **LineNum**: [159](https://github.com/Brilliant-Minds/Brilliant-Minds.github.io/blob/e9b4f2f1d14a67a061d3df840d20bfc6f3463e24/members.js#L159)

    @Brilliant-Minds/developers what do you think of this? Would it be necessary to add

**Comment by io4** [comment]
if (e.awards.hasOwnProperty(i)) {
//STUFF
}
May work ( https://jslinterrors.com/the-body-of-a-for-in-should-be-wrapped-in-an-if-statement )

**Comment by io4** [comment]
I belive it's more for when searching props. in objects, not arrays.
